# Generated by Django 6.0.5 on 2026-06-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_sessionprogress'),
        ('learners', '0001_initial'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.session')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.learnerprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentors.mentorprofile')),
            ],
        ),
    ]
