# Generated by Django 6.0.5 on 2026-05-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mentor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='session_videos/')),
                ('materials', models.FileField(blank=True, null=True, upload_to='session_materials/')),
                ('quiz', models.URLField(blank=True, null=True)),
                ('simulation', models.URLField(blank=True, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course')),
            ],
        ),
    ]
