# Generated by Django 6.0.5 on 2026-05-27 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='session',
            name='simulation',
        ),
        migrations.AddField(
            model_name='session',
            name='circuit_diagram',
            field=models.ImageField(blank=True, null=True, upload_to='circuit_diagrams/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.session')),
            ],
        ),
    ]
