# Generated by Django 6.0.5 on 2026-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_session_mentor_remove_session_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
