# Generated by Django 6.0.5 on 2026-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_mentor_course_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentors',
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
