# Generated by Django 6.0.5 on 2026-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_mentors_course_mentor'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mentor',
        ),
        migrations.AddField(
            model_name='course',
            name='mentors',
            field=models.ManyToManyField(blank=True, to='mentors.mentorprofile'),
        ),
    ]
