# Generated by Django 6.0.5 on 2026-06-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_sessionprogress'),
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mentors.mentorprofile'),
        ),
    ]
