# Generated by Django 6.0.2 on 2026-02-23 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('primary_expertise', models.CharField(max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('years_of_experience', models.CharField(choices=[('0_1', '0-1 years'), ('1_3', '1-3 years'), ('3_5', '3-5 years'), ('5_plus', '5+ years')], max_length=10)),
                ('bio', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='mentor/resumes/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mentor/certificates/')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='mentors.mentorprofile')),
            ],
        ),
    ]
